### ISSUE TITLE
rename -> TASK_STORE

### ISSUE THREAD

**Issue by asattelmaier** [AllanEd/oo_php_user_login#3]
https://github.com/AllanEd/oo_php_user_login/blob/723d1f0bbd0daf5c98f14f1b69cb70a1b67877a1/classes/class.taskStore.php#L5

**Comment by asattelmaier** [comment]
TASK_STORE_TABLE

**Comment by AllanEd** [comment]
look at extends from task!

**Comment by asattelmaier** [comment]
remove closing php tag

**Comment by asattelmaier** [comment]
delcare strict types
